repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: "v5.0.0"
      hooks:
          - id: check-case-conflict
          - id: check-merge-conflict
          - id: check-toml
          - id: check-json
            exclude: ^\.devcontainer/devcontainer\.json$
          - id: check-yaml
          - id: end-of-file-fixer
          - id: trailing-whitespace

    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: "v0.8.2"
      hooks:
          - id: ruff
            args: [--fix]
          - id: ruff-format

    - repo: https://github.com/RobertCraigie/pyright-python
      rev: "v1.1.390"
      hooks:
          - id: pyright

    - repo: https://github.com/rbubley/mirrors-prettier
      rev: "v3.4.2"
      hooks:
          - id: prettier
            args: ["--write"]

    - repo: https://github.com/sourcery-ai/sourcery
      rev: "v1.28.0"
      hooks:
          - id: sourcery
            args: [--diff=git diff HEAD, --no-summary]
