coverage:
    range: 70..100
    round: down
    precision: 1
    status:
        project:
            default:
                target: 90%
                threshold: 0.5%

ignore:
    - "pragma: no cover"
    - "if TYPE_CHECKING:"
