site_name: weba
repo_url: https://github.com/cj/weba
site_url: https://weba.cj.io
site_description: A Python library for building web UIs with a declarative, component-based approach. Features type-safe HTML elements, HTMX integration, and reusable components with both sync and async support.
site_author: CJ Lazell
edit_uri: edit/main/docs/
repo_name: cj/weba
copyright: Maintained by <a href="https://www.cj.io">cj</a>.

nav:
    - Home: README.md
    - Examples:
          - ui: examples/ui.md
          - component: examples/component.md
    - Modules: modules.md
plugins:
    - search
    - mkdocstrings:
          handlers:
              python:
                  paths: [weba]
theme:
    name: material
    feature:
        tabs: true
    palette:
        - media: "(prefers-color-scheme: light)"
          scheme: default
          primary: white
          accent: deep orange
          toggle:
              icon: material/brightness-7
              name: Switch to dark mode
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          primary: black
          accent: deep orange
          toggle:
              icon: material/brightness-4
              name: Switch to light mode
    icon:
        repo: fontawesome/brands/github

extra:
    social:
        - icon: fontawesome/brands/github
          link: https://github.com/cj/weba
        - icon: fontawesome/brands/python
          link: https://pypi.org/project/weba

markdown_extensions:
    - toc:
          permalink: true
    - pymdownx.arithmatex:
          generic: true
    - pymdownx.highlight:
          anchor_linenums: true
    - pymdownx.superfences
