[pytest]
; This will print to stdout
; addopts = --browser chromium -rP
; This will run in parallel
; addopts = --numprocesses auto
; This will run in an actual browser
; addopts = --headed --browser chromium
addopts = --browser chromium -rP
; base_url = http://localhost:3392
asyncio_mode = auto
env =
  WEBA_ENV=test
